# Generated by Django 5.0.6 on 2024-07-26 00:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='updated_date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='delete_date')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Product's category",
                'verbose_name_plural': "Products' categories",
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='updated_date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='delete_date')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Measure Unit',
                'verbose_name_plural': 'Measure Units',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='created_date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='updated_date')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='delete_date')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Product's category",
                'verbose_name_plural': "historical Products' categories",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='created_date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='updated_date')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='delete_date')),
                ('decount_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='offertIndicator')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical offer's indicator",
                'verbose_name_plural': "historical offer's indicators",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='created_date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='updated_date')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='delete_date')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Measure Unit',
                'verbose_name_plural': 'historical Measure Units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='updated_date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='delete_date')),
                ('decount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='offertIndicator')),
            ],
            options={
                'verbose_name': "offer's indicator",
                'verbose_name_plural': "offer's indicators",
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='created_date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='updated_date')),
                ('delete_date', models.DateField(blank=True, editable=False, verbose_name='delete_date')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name="Product's name")),
                ('description', models.TextField(verbose_name="Product's description")),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='path image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('measure_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Mesuare Unit')),
            ],
            options={
                'verbose_name': 'historical Base model',
                'verbose_name_plural': 'historical Base models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='updated_date')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='delete_date')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Product's name")),
                ('description', models.TextField(verbose_name="Product's description")),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='path image')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Mesuare Unit')),
            ],
            options={
                'verbose_name': 'Base model',
                'verbose_name_plural': 'Base models',
                'abstract': False,
            },
        ),
    ]
