# Generated by Django 5.0.6 on 2024-10-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_categoryproduct_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': "historical Offer's indicator", 'verbose_name_plural': "historical Offer's indicators"},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product', 'verbose_name_plural': 'historical Products'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': "Offer's indicator", 'verbose_name_plural': "Offer's indicators"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
